'use client'

import { useState, useEffect, useCallback } from 'react'
import { createClient } from '@/lib/supabase/client'
import { getSignedUrl } from '@/lib/storage'
import { FileText, Download, Loader2 } from 'lucide-react'
import { Skeleton } from '@/components/ui/skeleton'
import type { ChatAttachment } from '@/types/database'

const BUCKET = 'chat-files'

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function isImageMime(mimeType: string): boolean {
  return mimeType.startsWith('image/')
}

// CFG-FOLLOW-01: defense-in-depth check that the first folder segment
// of a storage path matches the caller's tenant. Wave 6a CFG-001 locked
// the chat-files bucket RLS to require this prefix on reads, so a signed
// URL for a wrongly-prefixed path wouldn't actually grant access to
// another tenant's file — but signed URLs are generated by Supabase's
// storage service BEFORE RLS evaluates, and once issued they bypass RLS
// entirely for the lifetime of the token. If a future bug plants a
// malicious storagePath into chat_messages.attachments (which is
// RLS-gated but not its contents validated on read), we don't want to
// hand out a signed URL that could work at all. Refuse to sign anything
// whose first segment isn't the current message's tenant.
function isPathOwnedByTenant(storagePath: string, tenantId: string): boolean {
  if (!storagePath || !tenantId) return false
  const firstSegment = storagePath.split('/')[0]
  return firstSegment === tenantId
}

function ImageAttachment({ attachment, tenantId }: { attachment: ChatAttachment; tenantId: string }) {
  const [url, setUrl] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const supabase = createClient()

  useEffect(() => {
    let cancelled = false
    async function fetchUrl() {
      if (!isPathOwnedByTenant(attachment.storagePath, tenantId)) {
        console.warn('[chat-attachment] refusing to sign URL for foreign tenant path')
        setLoading(false)
        return
      }
      const { url: signedUrl } = await getSignedUrl(supabase, BUCKET, attachment.storagePath, 3600)
      if (!cancelled && signedUrl) {
        setUrl(signedUrl)
        setLoading(false)
      }
    }
    fetchUrl()
    return () => { cancelled = true }
  }, [supabase, attachment.storagePath, tenantId])

  const handleClick = useCallback(async () => {
    // Re-fetch signed URL on click in case the cached one expired
    if (!isPathOwnedByTenant(attachment.storagePath, tenantId)) return
    const { url: freshUrl } = await getSignedUrl(supabase, BUCKET, attachment.storagePath, 3600)
    if (freshUrl) window.open(freshUrl, '_blank')
  }, [supabase, attachment.storagePath, tenantId])

  if (loading) {
    return <Skeleton className="h-40 w-48 rounded-lg" />
  }

  return (
    <button
      onClick={handleClick}
      className="block overflow-hidden rounded-lg border border-border-subtle hover:border-brand/50 transition-colors cursor-pointer"
      title={attachment.fileName}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={url ?? ''}
        alt={attachment.fileName}
        className="max-w-xs max-h-48 object-contain rounded-lg"
        loading="lazy"
        onError={(e) => {
          // Hide broken image, show fallback
          (e.target as HTMLImageElement).style.display = 'none'
        }}
      />
    </button>
  )
}

function DocumentAttachment({ attachment, tenantId }: { attachment: ChatAttachment; tenantId: string }) {
  const [downloading, setDownloading] = useState(false)
  const supabase = createClient()

  const handleClick = useCallback(async () => {
    if (!isPathOwnedByTenant(attachment.storagePath, tenantId)) {
      console.warn('[chat-attachment] refusing to sign URL for foreign tenant path')
      return
    }
    setDownloading(true)
    const { url } = await getSignedUrl(supabase, BUCKET, attachment.storagePath, 3600)
    if (url) window.open(url, '_blank')
    setDownloading(false)
  }, [supabase, attachment.storagePath, tenantId])

  return (
    <button
      onClick={handleClick}
      disabled={downloading}
      className="inline-flex items-center gap-2 rounded-lg bg-muted/50 px-3 py-2 text-xs hover:bg-muted transition-colors cursor-pointer border border-border-subtle"
      title={`Download ${attachment.fileName}`}
    >
      <FileText className="h-4 w-4 text-muted-foreground shrink-0" />
      <div className="min-w-0 text-left">
        <p className="truncate font-medium text-foreground/80 max-w-[160px]">
          {attachment.fileName}
        </p>
        <p className="text-muted-foreground">{formatFileSize(attachment.fileSize)}</p>
      </div>
      {downloading ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground shrink-0" />
      ) : (
        <Download className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
      )}
    </button>
  )
}

interface AttachmentDisplayProps {
  attachments: ChatAttachment[]
  // CFG-FOLLOW-01: tenantId comes from the enclosing chat_message row
  // (RLS-scoped, so trusted). Used to refuse signing URLs for paths
  // whose first folder segment doesn't belong to this tenant.
  tenantId: string
}

export function AttachmentDisplay({ attachments, tenantId }: AttachmentDisplayProps) {
  if (!attachments || attachments.length === 0) return null

  return (
    <div className="flex flex-wrap gap-2 mt-2">
      {attachments.map((att, i) =>
        isImageMime(att.mimeType) ? (
          <ImageAttachment key={`${att.storagePath}-${i}`} attachment={att} tenantId={tenantId} />
        ) : (
          <DocumentAttachment key={`${att.storagePath}-${i}`} attachment={att} tenantId={tenantId} />
        )
      )}
    </div>
  )
}
